import { getPrettyHostname } from './utils'

export const languages = [
  { value: 'bat', name: 'Batch Script (Windows)' },
  { value: 'clojure', name: 'Clojure' },
  { value: 'coffee', name: 'CoffeeScript' },
  { value: 'cpp', name: 'C++' },
  { value: 'csharp', name: 'C#' },
  { value: 'csp', name: 'Content Security Policy' },
  { value: 'css', name: 'CSS' },
  { value: 'dockerfile', name: 'Dockerfile' },
  { value: 'fsharp', name: 'F#' },
  { value: 'go', name: 'Go' },
  { value: 'graphql', name: 'GraphQL' },
  { value: 'handlebars', name: 'Handlebars' },
  { value: 'html', name: 'HTML' },
  { value: 'ini', name: 'INI' },
  { value: 'java', name: 'Java' },
  { value: 'javascript', name: 'JavaScript' },
  { value: 'json', name: 'JSON' },
  { value: 'kotlin', name: 'Kotlin' },
  { value: 'less', name: 'LESS' },
  { value: 'lua', name: 'Lua' },
  { value: 'markdown', name: 'Markdown' },
  { value: 'msdax', name: 'DAX (Data Analysis Expressions)' },
  { value: 'mysql', name: 'MySQL' },
  { value: 'objective-c', name: 'Objective-C' },
  { value: 'pascal', name: 'Pascal' },
  { value: 'perl', name: 'Perl' },
  { value: 'pgsql', name: 'PostgreSQL' },
  { value: 'php', name: 'PHP' },
  { value: 'plaintext', name: 'Plain Text' },
  { value: 'postiats', name: 'ATS (Applied Type System)' },
  { value: 'powerquery', name: 'Power Query' },
  { value: 'powershell', name: 'PowerShell' },
  { value: 'pug', name: 'Pug (formerly Jade)' },
  { value: 'python', name: 'Python' },
  { value: 'r', name: 'R' },
  { value: 'razor', name: 'Razor (CSHTML)' },
  { value: 'redis', name: 'Redis' },
  { value: 'redshift', name: 'Redshift SQL' },
  { value: 'restructuredtext', name: 'reStructuredText' },
  { value: 'ruby', name: 'Ruby' },
  { value: 'rust', name: 'Rust' },
  { value: 'sb', name: 'Small Basic' },
  { value: 'scheme', name: 'Scheme' },
  { value: 'scss', name: 'SCSS' },
  { value: 'shell', name: 'Shell Script (Bash)' },
  { value: 'sol', name: 'Solidity (Ethereum)' },
  { value: 'sql', name: 'SQL' },
  { value: 'st', name: 'Structured Text' },
  { value: 'swift', name: 'Swift' },
  { value: 'typescript', name: 'TypeScript' },
  { value: 'vb', name: 'Visual Basic' },
  { value: 'xml', name: 'XML' },
  { value: 'yaml', name: 'YAML' },
]

export const hostname = new URL(
  process.env.NEXT_PUBLIC_BASE_URL as string,
).toString()

export const prettyHostname = getPrettyHostname()
